#!/bin/bash

#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@54.171.131.77 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.254.252.97 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@54.171.131.77 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@63.33.67.168 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@63.33.57.84 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@52.211.165.104 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@54.154.237.109 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@63.32.98.104 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.241.241.66 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.242.236.11 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.244.165.105 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@18.202.244.134 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@54.229.67.153 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@52.208.226.203 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.254.222.226 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.250.249.63 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@63.32.111.186 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.247.46.2 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@52.210.125.171 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.244.138.202 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@54.171.213.251 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
