#!/bin/bash

#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@54.229.83.110 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@54.229.83.110 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@63.33.67.168 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@63.33.67.168 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@52.211.165.104 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@52.211.165.104 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@63.32.98.104 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@63.32.98.104 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.242.236.11 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.242.236.11 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@18.202.244.134 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@18.202.244.134 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@52.208.226.203 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@52.208.226.203 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.250.249.63 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.250.249.63 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.247.46.2 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.247.46.2 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
#sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.244.138.202 'rm -rf guest_share/network-inference-with-Blockchain'
sshpass -p mininet ssh -o StrictHostKeyChecking=no mininet@34.244.138.202 'cd guest_share/network-inference-with-Blockchain; git fetch --all; git reset --hard origin/iTopModifications'
